# File to Store Series ids from Fred API
BASE_SERIES_LIST = [
    # Group 1: Output & income (mostly Δlog):contentReference[oaicite:11]{index=11}
    ("Output & Income", "RPI", 5, "Real Personal Income"),
    ("Output & Income", "W875RX1", 5, "Real Personal Income Excluding Transfers"),
    ("Output & Income", "INDPRO", 5, "Industrial Production Index"),
    ("Output & Income", "IPFPNSS", 5, "IP: Final Products & Nonindustrial Supplies"),
    ("Output & Income", "IPFINAL", 5, "IP: Final Products (Market Group)"),
    ("Output & Income", "IPCONGD", 5, "IP: Consumer Goods"),
    ("Output & Income", "IPDCONGD", 5, "IP: Durable Consumer Goods"),
    ("Output & Income", "IPNCONGD", 5, "IP: Nondurable Consumer Goods"),
    ("Output & Income", "IPBUSEQ", 5, "IP: Business Equipment"),
    ("Output & Income", "IPMAT", 5, "IP: Materials"),
    ("Output & Income", "IPDMAT", 5, "IP: Durable Materials"),
    ("Output & Income", "IPNMAT", 5, "IP: Nondurable Materials"),
    ("Output & Income", "IPMANSICS", 5, "IP: Manufacturing (SIC)"),
    ("Output & Income", "IPB51222S", 5, "IP: Residential Utilities"),
    ("Output & Income", "IPFUELS", 5, "IP: Fuels"),
    ("Output & Income", "NAPMPI", 1, "ISM Manufacturing: Production Index"),
    ("Output & Income", "CUMFNS", 2, "Capacity Utilization: Manufacturing"),

    # Group 2: Labor market:contentReference[oaicite:12]{index=12}
    ("Labor Market", "HWI", 2, "Help-Wanted Index (best-effort)"),
    ("Labor Market", "HWIURATIO", 2, "Help-Wanted to Unemployed Ratio"),
    ("Labor Market", "CLF16OV", 5, "Civilian Labor Force"),
    ("Labor Market", "CE16OV", 5, "Civilian Employment"),
    ("Labor Market", "UNRATE", 2, "Unemployment Rate"),
    ("Labor Market", "UEMPMEAN", 2, "Average Duration of Unemployment"),
    ("Labor Market", "PAYEMS", 5, "All Employees: Total Nonfarm"),
    ("Labor Market", "USGOOD", 5, "All Employees: Goods-Producing"),
    ("Labor Market", "USCONS", 5, "All Employees: Construction"),
    ("Labor Market", "MANEMP", 5, "All Employees: Manufacturing"),
    ("Labor Market", "DMANEMP", 5, "All Employees: Durable Goods"),
    ("Labor Market", "NDMANEMP", 5, "All Employees: Nondurable Goods"),
    ("Labor Market", "SRVPRD", 5, "All Employees: Service-Providing"),
    ("Labor Market", "USTPU", 5, "All Employees: Trade, Transportation & Utilities"),
    ("Labor Market", "USTRADE", 5, "All Employees: Retail Trade"),
    ("Labor Market", "USFIRE", 5, "All Employees: Financial Activities"),
    ("Labor Market", "USGOVT", 5, "All Employees: Government"),
    ("Labor Market", "CES0600000007", 1, "Avg Weekly Hours: Goods-Producing"),
    ("Labor Market", "AWOTMAN", 1, "Avg Weekly Overtime Hours: Manufacturing"),
    ("Labor Market", "AWHMAN", 1, "Avg Weekly Hours: Manufacturing"),
    ("Labor Market", "NAPMEI", 1, "ISM Manufacturing: Employment Index"),
    ("Labor Market", "CES0600000008", 6, "Avg Hourly Earnings: Goods-Producing"),
    ("Labor Market", "CES2000000008", 6, "Avg Hourly Earnings: Construction"),
    ("Labor Market", "CES3000000008", 6, "Avg Hourly Earnings: Manufacturing"),

    # Group 3: Housing (counts; use Δlog):contentReference[oaicite:13]{index=13}
    ("Housing", "HOUST", 5, "Housing Starts: Total"),
    ("Housing", "HOUSTNE", 5, "Housing Starts: Northeast"),
    ("Housing", "HOUSTMW", 5, "Housing Starts: Midwest"),
    ("Housing", "HOUSTS", 5, "Housing Starts: South"),
    ("Housing", "HOUSTW", 5, "Housing Starts: West"),
    ("Housing", "PERMIT", 5, "New Private Housing Permits (SAAR)"),
    ("Housing", "PERMITNE", 5, "Permits: Northeast"),
    ("Housing", "PERMITMW", 5, "Permits: Midwest"),
    ("Housing", "PERMITS", 5, "Permits: South"),
    ("Housing", "PERMITW", 5, "Permits: West"),

    # Group 4: Consumption, orders, inventories:contentReference[oaicite:14]{index=14}
    ("Consumption/Orders/Inventories", "DPCERA3M086SBEA", 5, "Real PCE"),
    ("Consumption/Orders/Inventories", "CMRMTSPL", 5, "Real Manufacturing & Trade Sales"),
    ("Consumption/Orders/Inventories", "RSAFS", 5, "Retail and Food Services Sales"),
    ("Consumption/Orders/Inventories", "NAPM", 1, "ISM PMI Composite Index"),
    ("Consumption/Orders/Inventories", "NAPMNOI", 1, "ISM New Orders Index"),
    ("Consumption/Orders/Inventories", "NAPMSDI", 1, "ISM Supplier Deliveries Index"),
    ("Consumption/Orders/Inventories", "NAPMII", 1, "ISM Inventories Index"),
    ("Consumption/Orders/Inventories", "ACOGNO", 5, "New Orders: Consumer Goods"),
    ("Consumption/Orders/Inventories", "AMDMNO", 5, "New Orders: Durable Goods"),
    ("Consumption/Orders/Inventories", "ANDENO", 5, "New Orders: Nondefense Capital Goods"),
    ("Consumption/Orders/Inventories", "AMDMUO", 5, "Unfilled Orders: Durable Goods"),
    ("Consumption/Orders/Inventories", "BUSINV", 5, "Total Business Inventories"),
    ("Consumption/Orders/Inventories", "ISRATIO", 2, "Inventories-to-Sales Ratio"),
    ("Consumption/Orders/Inventories", "UMCSENT", 2, "Consumer Sentiment Index"),

    # Group 5: Money & credit:contentReference[oaicite:15]{index=15}
    ("Money & Credit", "M1SL", 6, "M1 Money Stock"),
    ("Money & Credit", "M2SL", 6, "M2 Money Stock"),
    ("Money & Credit", "M2REAL", 5, "Real M2"),
    ("Money & Credit", "AMBSL", 6, "Adjusted Monetary Base"),
    ("Money & Credit", "TOTRESNS", 6, "Total Reserves"),
    ("Money & Credit", "NONBORRES", 6, "Nonborrowed Reserves"),
    ("Money & Credit", "BUSLOANS", 6, "Commercial & Industrial Loans"),
    ("Money & Credit", "REALLN", 6, "Real Estate Loans (All Commercial Banks)"),
    ("Money & Credit", "NONREVSL", 6, "Total Nonrevolving Credit"),
    ("Money & Credit", "MZMSL", 6, "MZM Money Stock"),
    ("Money & Credit", "DTCOLNVHFNM", 6, "Consumer Motor Vehicle Loans"),
    ("Money & Credit", "DTCTHFNM", 6, "Total Consumer Loans/Leases"),
    ("Money & Credit", "INVEST", 6, "Securities in Bank Credit"),

    # Group 6: Interest & exchange rates:contentReference[oaicite:16]{index=16}
    ("Rates/FX", "FEDFUNDS", 2, "Effective Federal Funds Rate"),
    ("Rates/FX", "CPF3M", 2, "3-Month AA Financial Commercial Paper (post-1997)"),
    ("Rates/FX", "M13002US35620M156NNBR", 2, "3-Month Commercial Paper (pre-1997, for splice)"),
    ("Rates/FX", "TB3MS", 2, "3-Month Treasury Bill"),
    ("Rates/FX", "TB6MS", 2, "6-Month Treasury Bill"),
    ("Rates/FX", "GS1", 2, "1-Year Treasury"),
    ("Rates/FX", "GS5", 2, "5-Year Treasury"),
    ("Rates/FX", "GS10", 2, "10-Year Treasury"),
    ("Rates/FX", "AAA", 2, "Moody's Aaa"),
    ("Rates/FX", "BAA", 2, "Moody's Baa"),
    ("Rates/FX", "TWEXMMTH", 5, "Trade-Weighted Dollar Index (Major Currencies)"),
    ("Rates/FX", "EXSZUS", 5, "Switzerland/US FX"),
    ("Rates/FX", "EXJPUS", 5, "Japan/US FX"),
    ("Rates/FX", "EXUSUK", 5, "US/UK FX"),
    ("Rates/FX", "EXCAUS", 5, "Canada/US FX"),

    # Group 7: Prices:contentReference[oaicite:17]{index=17}
    ("Prices", "PPIFGS", 6, "PPI: Finished Goods"),
    ("Prices", "PPIFCG", 6, "PPI: Finished Consumer Goods"),
    ("Prices", "PPIITM", 6, "PPI: Intermediate Materials"),
    ("Prices", "PPICRM", 6, "PPI: Crude Materials"),
    ("Prices", "MCOILWTICO", 6, "Crude Oil (WTI), monthly"),
    ("Prices", "PPICMM", 6, "PPI: Metals & Metal Products"),
    ("Prices", "NAPMPRI", 1, "ISM Manufacturing: Prices Index"),
    ("Prices", "CPIAUCSL", 6, "CPI: All Items"),
    ("Prices", "CPIAPPSL", 6, "CPI: Apparel"),
    ("Prices", "CPITRNSL", 6, "CPI: Transportation"),
    ("Prices", "CPIMEDSL", 6, "CPI: Medical Care"),
    ("Prices", "CUSR0000SAC", 6, "CPI: Commodities"),
    ("Prices", "CUUR0000SAD", 6, "CPI: Durables"),
    ("Prices", "CUSR0000SAS", 6, "CPI: Services"),
    ("Prices", "CPIULFSL", 6, "CPI: Less Food"),
    ("Prices", "CUUR0000SA0L2", 6, "CPI: Less Shelter"),
    ("Prices", "CUSR0000SA0L5", 6, "CPI: Less Medical Care"),
    ("Prices", "PCEPI", 6, "PCE Price Index"),
    ("Prices", "DDURRG3M086SBEA", 6, "PCE Deflator: Durables"),
    ("Prices", "DNDGRG3M086SBEA", 6, "PCE Deflator: Nondurables"),
    ("Prices", "DSERRG3M086SBEA", 6, "PCE Deflator: Services"),

    # Group 8: Stock market (use Δlog for price; levels for yields/ratios):contentReference[oaicite:18]{index=18}
    ("Stock Market", "SP500", 5, "S&P 500 (daily -> monthly avg)"),
    ("Stock Market", "SPDIVY", 1, "S&P 500 Dividend Yield"),
    ("Stock Market", "CAPE", 1, "Shiller CAPE P/E Ratio"),
]


BASE_SERIES_DICT = {
    'Output & Income': {
        'Capacity Utilization: Manufacturing': 'CUMFNS',
        'IP: Business Equipment': 'IPBUSEQ',
        'IP: Consumer Goods': 'IPCONGD',
        'IP: Durable Consumer Goods': 'IPDCONGD',
        'IP: Durable Materials': 'IPDMAT',
        'IP: Final Products & Nonindustrial Supplies': 'IPFPNSS',
        'IP: Final Products (Market Group)': 'IPFINAL',
        'IP: Fuels': 'IPFUELS',
        'IP: Manufacturing (SIC)': 'IPMANSICS',
        'IP: Materials': 'IPMAT',
        'IP: Nondurable Consumer Goods': 'IPNCONGD',
        'IP: Nondurable Materials': 'IPNMAT',
        'IP: Residential Utilities': 'IPB51222S',
        'ISM Manufacturing: Production Index': 'NAPMPI',
        'Industrial Production Index': 'INDPRO',
        'Real Personal Income': 'RPI',
        'Real Personal Income Excluding Transfers': 'W875RX1'
    },
    'Labor Market': {
        'All Employees: Construction': 'USCONS',
        'All Employees: Durable Goods': 'DMANEMP',
        'All Employees: Financial Activities': 'USFIRE',
        'All Employees: Goods-Producing': 'USGOOD',
        'All Employees: Government': 'USGOVT',
        'All Employees: Manufacturing': 'MANEMP',
        'All Employees: Nondurable Goods': 'NDMANEMP',
        'All Employees: Retail Trade': 'USTRADE',
        'All Employees: Service-Providing': 'SRVPRD',
        'All Employees: Total Nonfarm': 'PAYEMS',
        'All Employees: Trade, Transportation & Utilities': 'USTPU',
        'Average Duration of Unemployment': 'UEMPMEAN',
        'Avg Hourly Earnings: Construction': 'CES2000000008',
        'Avg Hourly Earnings: Goods-Producing': 'CES0600000008',
        'Avg Hourly Earnings: Manufacturing': 'CES3000000008',
        'Avg Weekly Hours: Goods-Producing': 'CES0600000007',
        'Avg Weekly Hours: Manufacturing': 'AWHMAN',
        'Avg Weekly Overtime Hours: Manufacturing': 'AWOTMAN',
        'Civilian Employment': 'CE16OV',
        'Civilian Labor Force': 'CLF16OV',
        'Help-Wanted Index (best-effort)': 'HWI',
        'Help-Wanted to Unemployed Ratio': 'HWIURATIO',
        'ISM Manufacturing: Employment Index': 'NAPMEI',
        'Unemployment Rate': 'UNRATE'
    },
    'Housing': {
        'Housing Starts: Midwest': 'HOUSTMW',
        'Housing Starts: Northeast': 'HOUSTNE',
        'Housing Starts: South': 'HOUSTS',
        'Housing Starts: Total': 'HOUST',
        'Housing Starts: West': 'HOUSTW',
        'New Private Housing Permits (SAAR)': 'PERMIT',
        'Permits: Midwest': 'PERMITMW',
        'Permits: Northeast': 'PERMITNE',
        'Permits: South': 'PERMITS',
        'Permits: West': 'PERMITW'
    },
    'Consumption/Orders/Inventories': {
        'Consumer Sentiment Index': 'UMCSENT',
        'ISM Inventories Index': 'NAPMII',
        'ISM New Orders Index': 'NAPMNOI',
        'ISM PMI Composite Index': 'NAPM',
        'ISM Supplier Deliveries Index': 'NAPMSDI',
        'Inventories-to-Sales Ratio': 'ISRATIO',
        'New Orders: Consumer Goods': 'ACOGNO',
        'New Orders: Durable Goods': 'AMDMNO',
        'New Orders: Nondefense Capital Goods': 'ANDENO',
        'Real Manufacturing & Trade Sales': 'CMRMTSPL',
        'Real PCE': 'DPCERA3M086SBEA',
        'Retail and Food Services Sales': 'RSAFS',
        'Total Business Inventories': 'BUSINV',
        'Unfilled Orders: Durable Goods': 'AMDMUO'
    },
    'Money & Credit': {
        'Adjusted Monetary Base': 'AMBSL',
        'Commercial & Industrial Loans': 'BUSLOANS',
        'Consumer Motor Vehicle Loans': 'DTCOLNVHFNM',
        'M1 Money Stock': 'M1SL',
        'M2 Money Stock': 'M2SL',
        'MZM Money Stock': 'MZMSL',
        'Nonborrowed Reserves': 'NONBORRES',
        'Real Estate Loans (All Commercial Banks)': 'REALLN',
        'Real M2': 'M2REAL',
        'Securities in Bank Credit': 'INVEST',
        'Total Consumer Loans/Leases': 'DTCTHFNM',
        'Total Nonrevolving Credit': 'NONREVSL',
        'Total Reserves': 'TOTRESNS'
    },
    'Rates/FX': {
        '1-Year Treasury': 'GS1',
        '10-Year Treasury': 'GS10',
        '3-Month AA Financial Commercial Paper (post-1997)': 'CPF3M',
        '3-Month Commercial Paper (pre-1997, for splice)': 'M13002US35620M156NNBR',
        '3-Month Treasury Bill': 'TB3MS',
        '5-Year Treasury': 'GS5',
        '6-Month Treasury Bill': 'TB6MS',
        'Canada/US FX': 'EXCAUS',
        'Effective Federal Funds Rate': 'FEDFUNDS',
        'Japan/US FX': 'EXJPUS',
        "Moody's Aaa": 'AAA',
        "Moody's Baa": 'BAA',
        'Switzerland/US FX': 'EXSZUS',
        'Trade-Weighted Dollar Index (Major Currencies)': 'TWEXMMTH',
        'US/UK FX': 'EXUSUK'
    },
    'Prices': {
        'CPI: All Items': 'CPIAUCSL',
        'CPI: Apparel': 'CPIAPPSL',
        'CPI: Commodities': 'CUSR0000SAC',
        'CPI: Durables': 'CUUR0000SAD',
        'CPI: Less Food': 'CPIULFSL',
        'CPI: Less Medical Care': 'CUSR0000SA0L5',
        'CPI: Less Shelter': 'CUUR0000SA0L2',
        'CPI: Medical Care': 'CPIMEDSL',
        'CPI: Services': 'CUSR0000SAS',
        'CPI: Transportation': 'CPITRNSL',
        'Crude Oil (WTI), monthly': 'MCOILWTICO',
        'ISM Manufacturing: Prices Index': 'NAPMPRI',
        'PCE Deflator: Durables': 'DDURRG3M086SBEA',
        'PCE Deflator: Nondurables': 'DNDGRG3M086SBEA',
        'PCE Deflator: Services': 'DSERRG3M086SBEA',
        'PCE Price Index': 'PCEPI',
        'PPI: Crude Materials': 'PPICRM',
        'PPI: Finished Consumer Goods': 'PPIFCG',
        'PPI: Finished Goods': 'PPIFGS',
        'PPI: Intermediate Materials': 'PPIITM',
        'PPI: Metals & Metal Products': 'PPICMM'
    },
    'Stock Market': {
        'S&P 500 (daily -> monthly avg)': 'SP500',
        'S&P 500 Dividend Yield': 'SPDIVY',
        'Shiller CAPE P/E Ratio': 'CAPE'
    }
}