# File to Store Series ids from Fred API
# Populated from fetch_fred_data.py BASE_SERIES

FRED_SERIES = {
    'Output_Income': {
        'Real Personal Income': 'RPI',
        'Real Personal Income Excluding Transfers': 'W875RX1',
        'Industrial Production Index': 'INDPRO',
        'IP: Final Products & Nonindustrial Supplies': 'IPFPNSS',
        'IP: Final Products (Market Group)': 'IPFINAL',
        'IP: Consumer Goods': 'IPCONGD',
        'IP: Durable Consumer Goods': 'IPDCONGD',
        'IP: Nondurable Consumer Goods': 'IPNCONGD',
        'IP: Business Equipment': 'IPBUSEQ',
        'IP: Materials': 'IPMAT',
        'IP: Durable Materials': 'IPDMAT',
        'IP: Nondurable Materials': 'IPNMAT',
        'IP: Manufacturing (SIC)': 'IPMANSICS',
        'IP: Residential Utilities': 'IPB51222S',
        'IP: Fuels': 'IPFUELS',
        'Capacity Utilization: Manufacturing': 'CUMFNS'
    },
    'Labor_Market': {
        'Civilian Labor Force': 'CLF16OV',
        'Civilian Employment': 'CE16OV',
        'Unemployment Rate': 'UNRATE',
        'Average Duration of Unemployment': 'UEMPMEAN',
        'All Employees: Total Nonfarm': 'PAYEMS',
        'All Employees: Goods-Producing': 'USGOOD',
        'All Employees: Construction': 'USCONS',
        'All Employees: Manufacturing': 'MANEMP',
        'All Employees: Durable Goods': 'DMANEMP',
        'All Employees: Nondurable Goods': 'NDMANEMP',
        'All Employees: Service-Providing': 'SRVPRD',
        'All Employees: Trade, Transportation & Utilities': 'USTPU',
        'All Employees: Retail Trade': 'USTRADE',
        'All Employees: Financial Activities': 'USFIRE',
        'All Employees: Government': 'USGOVT',
        'Avg Weekly Hours: Goods-Producing': 'CES0600000007',
        'Avg Weekly Overtime Hours: Manufacturing': 'AWOTMAN',
        'Avg Weekly Hours: Manufacturing': 'AWHMAN',
        'Avg Hourly Earnings: Goods-Producing': 'CES0600000008',
        'Avg Hourly Earnings: Construction': 'CES2000000008',
        'Avg Hourly Earnings: Manufacturing': 'CES3000000008'
    },
    'Housing': {
        'Housing Starts: Total': 'HOUST',
        'Housing Starts: Northeast': 'HOUSTNE',
        'Housing Starts: Midwest': 'HOUSTMW',
        'Housing Starts: South': 'HOUSTS',
        'Housing Starts: West': 'HOUSTW',
        'New Private Housing Permits (SAAR)': 'PERMIT',
        'Permits: Northeast': 'PERMITNE',
        'Permits: Midwest': 'PERMITMW',
        'Permits: South': 'PERMITS',
        'Permits: West': 'PERMITW'
    },
    'Consumption_Orders_Inventories': {
        'Real PCE': 'DPCERA3M086SBEA',
        'Real Manufacturing & Trade Sales': 'CMRMTSPL',
        'Retail and Food Services Sales': 'RSAFS',
        'New Orders: Consumer Goods': 'ACOGNO',
        'New Orders: Nondefense Capital Goods': 'ANDENO',
        'Unfilled Orders: Durable Goods': 'AMDMUO',
        'Total Business Inventories': 'BUSINV',
        'Inventories-to-Sales Ratio': 'ISRATIO',
        'Consumer Sentiment Index': 'UMCSENT'
    },
    'Money_Credit': {
        'M1 Money Stock': 'M1SL',
        'M2 Money Stock': 'M2SL',
        'Real M2': 'M2REAL',
        'Adjusted Monetary Base': 'AMBSL',
        'Total Reserves': 'TOTRESNS',
        'Nonborrowed Reserves': 'NONBORRES',
        'Commercial & Industrial Loans': 'BUSLOANS',
        'Real Estate Loans (All Commercial Banks)': 'REALLN',
        'Total Nonrevolving Credit': 'NONREVSL',
        'MZM Money Stock': 'MZMSL',
        'Consumer Motor Vehicle Loans': 'DTCOLNVHFNM',
        'Total Consumer Loans/Leases': 'DTCTHFNM',
        'Securities in Bank Credit': 'INVEST'
    },
    'Rates_FX': {
        'Effective Federal Funds Rate': 'FEDFUNDS',
        '3-Month AA Financial Commercial Paper (post-1997)': 'CPF3M',
        '3-Month Commercial Paper (pre-1997, for splice)': 'M13002US35620M156NNBR',
        '3-Month Treasury Bill': 'TB3MS',
        '6-Month Treasury Bill': 'TB6MS',
        '1-Year Treasury': 'GS1',
        '5-Year Treasury': 'GS5',
        '10-Year Treasury': 'GS10',
        "Moody's Aaa": 'AAA',
        "Moody's Baa": 'BAA',
        'Switzerland/US FX': 'EXSZUS',
        'Japan/US FX': 'EXJPUS',
        'US/UK FX': 'EXUSUK',
        'Canada/US FX': 'EXCAUS'
    },
    'Prices': {
        'PPI: Finished Goods': 'PPIFGS',
        'PPI: Finished Consumer Goods': 'PPIFCG',
        'PPI: Intermediate Materials': 'PPIITM',
        'PPI: Crude Materials': 'PPICRM',
        'Crude Oil (WTI), monthly': 'MCOILWTICO',
        'PPI: Metals & Metal Products': 'PPICMM',
        'CPI: All Items': 'CPIAUCSL',
        'CPI: Apparel': 'CPIAPPSL',
        'CPI: Transportation': 'CPITRNSL',
        'CPI: Medical Care': 'CPIMEDSL',
        'CPI: Commodities': 'CUSR0000SAC',
        'CPI: Durables': 'CUUR0000SAD',
        'CPI: Services': 'CUSR0000SAS',
        'CPI: Less Food': 'CPIULFSL',
        'CPI: Less Shelter': 'CUUR0000SA0L2',
        'CPI: Less Medical Care': 'CUSR0000SA0L5',
        'PCE Price Index': 'PCEPI',
        'PCE Deflator: Durables': 'DDURRG3M086SBEA',
        'PCE Deflator: Nondurables': 'DNDGRG3M086SBEA',
        'PCE Deflator: Services': 'DSERRG3M086SBEA'
    },
    'Stock_Market': {
        'S&P 500 (daily -> monthly avg)': 'SP500'
    }
}